[workspace]
members = ["crates/indexer", "crates/schema"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
bcs = "0.1"
clap = { version = "4.5", features = ["derive", "env"] }
dotenvy = "0.15"
futures = "0.3"
hex = "0.4"
mongodb = "3.1"
move-core-types = { git = "https://github.com/MystenLabs/sui", package = "move-core-types" }
once_cell = "1.20"
regex = "1.11"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sui-types = { git = "https://github.com/MystenLabs/sui", package = "sui-types" }
sui-sdk-types = { git = "https://github.com/MystenLabs/sui-rust-sdk", package = "sui-sdk-types" }
tokio = { version = "1.40", features = ["full", "signal"] }
tokio-util = "0.7"
tracing = "0.1"
telemetry-subscribers = { git = "https://github.com/MystenLabs/sui", package = "telemetry-subscribers" }
url = "2.5"
